### ISSUE TITLE
Lib issue

### ISSUE THREAD

**Issue by farias06** [ARIAS-Joseph/HUD-diving-informations#1]
My test : 
**$ python3 CreateBgForVideoWithFFMEG.py** 
Traceback (most recent call last):
  File "/home/..../.../HUD-diving-informations/CreateBgForVideoWithFFMEG.py", line 13, in <module>
    import plotly.graph_objects as go
ModuleNotFoundError: No module named 'plotly'

**$ pip3 install plotly**
Defaulting to user installation because normal site-packages is not writeable
Collecting plotly
  Downloading plotly-5.15.0-py2.py3-none-any.whl (15.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 42.7 MB/s eta 0:00:00
Collecting tenacity>=6.2.0
  Downloading tenacity-8.2.2-py3-none-any.whl (24 kB)
Requirement already satisfied: packaging in /home/..../.local/lib/python3.10/site-packages (from plotly) (23.1)
Installing collected packages: tenacity, plotly
Successfully installed plotly-5.15.0 tenacity-8.2.2

**$ pip3 install kaleido**
Defaulting to user installation because normal site-packages is not writeable
Collecting kaleido
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 20.9 MB/s eta 0:00:00
Installing collected packages: kaleido
Successfully installed kaleido-0.2.1

I  have install pipreqs : pip3 install pipreqs :

$ cat  requirements.txt 
Pillow==9.4.0
Pillow==9.0.1
Pillow==10.0.0
plotly==5.15.0

**Comment by farias06** [comment]
Traceback (most recent call last):
  File "/home/arias/GIT/HUD-diving-informations/CreateBgForVideoWithFFMEG.py", line 286, in <module>
    os.system(my_ffmpeg+' -framerate 1 -start_number '+my_start_time+'  -s '+str(my_h)+'x'+str(my_w)+' -i '+my_tempFolder+'/pic-%04d.png -c:v png -r 30 '+my_videooutput);
TypeError: can only concatenate str (not "int") to str

**Comment by farias06** [comment]
New issue on linux : 
**$ time python3 CreateBgForVideoWithFFMEG.py** 
Traceback (most recent call last):
  File "/home/arias/GIT/HUD-diving-informations/CreateBgForVideoWithFFMEG.py", line 15, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named '**tkinter**'

real	0m0,174s
user	0m0,146s
sys	0m0,028s

**Comment by farias06** [comment]
Perfect, the last commit works on  Linux (FYI) : 

My processor : x86_64
My OS : Linux
My OS Relase : Linux-5.15.0-78-generic-x86_64-with-glibc2.35
My Python Version :3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
My FFMPEG : ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
